### ISSUE TITLE
Add "autoprefixer" binary

### ISSUE THREAD

**Issue by iBobik** [ai/autoprefixer-cli#1]
Is it able to also install "autoprefixer" binary, not only "autoprefixer-cli" or symlink to it? Legacy software will welcome it :-)

**Comment by ai** [comment]
@iBobik it is very bad, when npm package has binary with different name. You can create `autoprefixer` binary very easy.

**Comment by iBobik** [comment]
Yes,  I already created the link very easily, but for future users it will be helpful if package creates it automatically.

Jan Pobořil
http://honza.poboril.cz/
1. 10. 2015 v 8:01, Andrey Sitnik notifications@github.com:
