### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by bdkjones** [ai/autoprefixer-cli#3]
Your `package.json` file lists the Autoprefixer dependency as `^6.2.0`. Autoprefixer is now on version 7, so installing this component won't install the latest version of Autoprefixer.

**Comment by ai** [comment]
Ouh, I forgot to add Deprecated notice in docs.

This project is deprecated. Uses postcss-cli.

If you want to maintain it and save it from deprecating, I can give you access.

**Comment by bdkjones** [comment]
`postcss-cli` is a complicated configuration nightmare. I don't want to write out a ton of configuration; I just want to call Autoprefixer from the command line. Unless I'm mistaken, nothing has changed in Autoprefixer 7 that would stop this package from working, right?

**Comment by ai** [comment]
Is it impossible to run Autoprefixer by postcss-cli without config?

Also, why you explain it to me? If you want single task tool, just become a maintainer of those projects. Port all new options from 7.0 to this CLI and release new version.

**Comment by ai** [comment]
Here is zero-config one line snippet to run Autoprefixer by postcss-cli:

```
postcss *.css --use autoprefixer -d build/
```

Why it doesn't work for you?

**Comment by bdkjones** [comment]
Well, a large part of the reason I've stuck with this package is because `postcss-cli`, like all modern JavaScript packages, is insanely bloated. I bundle these things in an app and `postcss-cli` requires *TWENTY THREE POINT SEVEN* megabytes of space on disk, as shown in this screenshot of a folder' after I ran `npm install postcss-cli` in it:

<img width="289" alt="screen shot 2017-08-10 at 23 27 22" src="https://user-images.githubusercontent.com/926566/29203159-86abf5e8-7e23-11e7-9434-cd338675c119.png">

(Don't be misled by the 13.9MB at the top. That's the amount of actual DATA in this folder, but because it's spread over a ton of tiny files and the minimum block size on a disk is 4KB, the actual amount of disk space consumed is 23.7MB.)

There are entire operating systems that are less than 23.7MB and all `postcss-cli` is supposed to handle is parsing some command line arguments. 

The bloat in modern JavaScript is really frustrating. There's simply no way that parsing a few commands should require 23.7MB of code.

**Comment by ai** [comment]
Yeap. It is sad. Let’s fix it :).

Could you check (manually or by some tools), who takes biggest parts of `node_modules`?

I can write to `postcss-cli` authors and remove biggest not-really-important dependencies.

**Comment by bdkjones** [comment]
Well, just looking at the dependency tree that npm created in my Terminal window when I installed, the largest offender appears to be the `fsevents` package. (`fsevents` apparently depends on every single piece of JavaScript ever written anywhere.)

And then there's the usual crap that should NEVER have been made a package to start with. Things like `isarray` and `is-directory`. You guys don't depend on those directly, but some of the stuff you're using does. Each one of these packages comes with another folder, another `README`, another `LICENSE` file, another set of `test` and `src` and other garbage that just adds up. It's the usual story.

**Comment by ai** [comment]
So, what is the `node_modules` size difference between `autoprefixer-cli` and `postcss-cli + autoprefixer`?

**Comment by bdkjones** [comment]
`autoprefixer-cli` is 12.4MB on disk. `postcss-cli` is 23.7MB. 

So, `postcss-cli` is roughly 100% larger.

**Comment by bdkjones** [comment]
Also, I can't figure out how to use `postcss-cli` to run `-v` on Autoprefixer. In other words, I want the version of Autoprefixer. What is the postcss command to get that?

**Comment by ai** [comment]
You need not a `postcss` command, but `npm` command for it. You can try from:

```
npm list | grep autoprefixer
```

**Comment by ai** [comment]
@bdkjones can you also check size of `node_modules` with `autoprefixer` only? To be sure that size goes not from huge Can I Use database (it could become bigger after old Autoprefixer 6 release)

**Comment by bdkjones** [comment]
Autoprefixer alone takes `5.3MB` on disk.

**Comment by ai** [comment]
Strange. `caniuse-lite` should be at least 7 MB. Do you install `autoprefixer` to fresh `node_modules` or just check `node_modules/autoprefixer` size?

Sorry, I can do it by my own, because in Linux we have different fs chunks system.

**Comment by bdkjones** [comment]
Also, that approach for getting the version is super hacky. What if I wanted to get the help output from autoprefixer (`-h`)? 

I think one of the requirements of a CLI is the ability to (1) get the version of a tool and (2) get its help/usage right in the Terminal. That `postcss-cli` doesn't provide this for the tools it is supposed to be providing a CLI for seems like a failure.

**Comment by bdkjones** [comment]
I created a new, empty folder. Then ran `npm install autoprefixer` in that folder. I see the `caniuse-lite` package listed in `node_modules`.  It is 3MB on disk.

**Comment by ai** [comment]
@bdkjones there is always an option to become a maintainer for `autoprefixer-cli` and update it by your own :).

In this case you can create the best `--help` and `-v` output :).

**Comment by ai** [comment]
@ben-eb wow, you did really great work!

> I see the caniuse-lite package listed in node_modules. It is 3MB on disk.

**Comment by ai** [comment]
Here is postcss-cli dependencies https://github.com/postcss/postcss-cli/blob/master/package.json#L19-L33

I long list, but most of them needed for good UX.

Why do you need this Autoprefixer CLI? Maybe there is a some better way?

**Comment by bdkjones** [comment]
Yea, I may end up doing that. But that entails headaches in the future. The trouble is that you guys decided to migrate to a new CLI package that's 100% larger and doesn't even do all the things the old one did. I see some issues over on `postcss-cli` where folks are wondering how to do things like `-v` or `-h`.

**Comment by ai** [comment]
@bdkjones “decided to migrate” — it is not the real history ;). Let’s me tell the real story:

1. In the past, I supported Autoprefixer, PostCSS and Autoprefixer CLI.
2. Right now I have more open source projects. So right now I have no time for Autoprefixer CLI.
3. So here is my choice — reduce my time for sleep or increase your `node_modules` in 10 MB.

What will you prefer in my position? Decrease your sleeping time or increase `node_modules` in 10 MB?

**Comment by bdkjones** [comment]
Ha, I hear you. I’m more frustrated with the PostCSS team than I am with Autoprefixer.

**Comment by ai** [comment]
I am the PostCSS team ;). If you have any problem with PostCSS size or PostCSS parser — I will fix it.

PostCSS CLI team is a different team ;).

**Comment by bdkjones** [comment]
Ah, I see. I assumed they were related.

**Comment by bdkjones** [comment]
Quick question: if I run `build:lib`, I don't see `babel-core` used anywhere in the resulting `binary.js` file. Is it the case that babel is NOT a dependency when this package is built into a library? It seems to run fine without it, but just wanted to confirm. Thanks!

**Comment by ai** [comment]
@bdkjones `babel-core` is in `dependencies` to install `autoprefixer-cli` from GitHub. When you will run `build` task, build scripts will generate new `package.json` and remove `babel-core` from `dependencies`.
