### ISSUE TITLE
(bug?) No support for "browserslist": "extends ...",

### ISSUE THREAD

**Issue by MisterTicot** [ai/autoprefixer-cli#5]
In my `package.json` I'm using `"browserslist": "extends @kisbox/browserslist-config"` and autoprefixer-cli is returning:

> autoprefixer-cli: Unknown browser query \`extends @kisbox/browserslist-config\`

It's called from a `package.json` script.

**Comment by ai** [comment]
We do not support `autoprefixer-cli` anymore. Seems like it use old version of Autoprefixer and Browserslist.

Use `postcss-cli` instead.

**Comment by MisterTicot** [comment]
Thanks
